apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency.name" . }}
spec:
  selector:
    {{- include "muffin-currency.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}