apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.name" . }}-env
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
data:
  JDK_JAVA_OPTIONS: {{ .Values.javaOpts | quote }}