apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.name" . }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "muffin-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "muffin-wallet.selectorLabels" . | nindent 8 }}
      annotations:
        # Автоматическая инструментация через OpenTelemetry Operator
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      volumes:
        - name: application-config-volume
          configMap:
            name: {{ include "muffin-wallet.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: application-config-volume
              mountPath: /app/config
          envFrom:
            - secretRef:
                name: {{ include "muffin-wallet.name" . }}
            - configMapRef:
                name: {{ include "muffin-wallet.name" . }}-env
          env:
            # OpenTelemetry конфигурация
            - name: OTEL_SERVICE_NAME
              value: "muffin-wallet"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.default.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://otel-collector.default.svc.cluster.local:4318/v1/logs"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=muffin-wallet,service.namespace={{ .Release.Namespace }}"
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}